'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,Check,Clock3,Compass,HeartHandshake,Languages,MapPin,Menu,MessageCircle,Minus,Plane,Plus,ShieldCheck,Sparkles,Users,X} from 'lucide-react';
const wa=(m:string)=>`https://wa.me/212665422808?text=${encodeURIComponent(m)}`;
const journey=[['Avant le départ','Préparer','Documents & visa','Conseils pratiques','Préparation spirituelle'],['Le voyage','Accompagner','Vol & transfert','Accueil du groupe','Assistance continue'],['Makkah','S’élever','Hôtel & Haram','Programme spirituel','Accompagnement'],['Médine','Se recueillir','Masjid An-Nabawi','Ziyarat','Moments spirituels'],['Le retour','Prolonger','Transfert & vol','Suivi du groupe','Souvenirs partagés']];
function Mark(){return <div className="mark"><span>F</span><b>G</b></div>}
function WhatsApp({label='Parler à Othmane',message='Salam Othmane, je souhaite avoir des informations concernant une Omra.'}:{label?:string,message?:string}){return <a className="btn whats" href={wa(message)} target="_blank"><MessageCircle size={18}/>{label}</a>}
export default function Home(){
 const [menu,setMenu]=useState(false),[step,setStep]=useState(0),[match,setMatch]=useState(0),[answers,setAnswers]=useState<Record<number,string>>({}),[city,setCity]=useState<'Makkah'|'Médine'>('Makkah'),[senior,setSenior]=useState(false),[lang,setLang]=useState<'FR'|'AR'>('FR');
 const [family,setFamily]=useState({adultes:2,enfants:0,aines:0});
 const qs=[['Avec qui voyagez-vous ?','Seul(e)','En couple','En famille','En groupe'],['Quel confort recherchez-vous ?','Essentiel','Confort','Premium'],['Quelle proximité souhaitez-vous ?','Très proche du Haram','Un bon équilibre','Le budget d’abord'],['Quel accompagnement préférez-vous ?','Classique','Renforcé','Très personnalisé']];
 const rec=useMemo(()=>answers[1]==='Premium'?'Omra Sérénité Premium':answers[1]==='Essentiel'?'Omra Essentielle':'Omra Confort',[answers]);
 const change=(k:keyof typeof family,d:number)=>setFamily(v=>({...v,[k]:Math.max(k==='adultes'?1:0,v[k]+d)}));
 if(lang==='AR') return <ArabicHome onFrench={()=>setLang('FR')}/>;
 return <main className={senior?'senior':''}>
  <header><a href="#top" className="brand"><Mark/><span><b>FANTASTIC GOLDEN</b><small>TAROUDANT · MAROC</small></span></a><nav className={menu?'open':''}><a href="#voyage">L’expérience</a><a href="#match">Omra Match</a><a href="#guide">Guide</a><a href="#famille">Familles</a></nav><div className="actions"><button onClick={()=>setLang('AR')}><Languages size={16}/>العربية</button><button className="elder" onClick={()=>setSenior(!senior)}>Mode aînés</button><WhatsApp label="WhatsApp"/><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
  <section className="hero" id="top"><div className="heroBg"/><div className="heroContent"><p className="kicker">VOYAGES OMRA · ACCOMPAGNEMENT HUMAIN</p><h1>FANTASTIC<br/><em>GOLDEN</em></h1><div className="arabic" dir="rtl">خير رفيق للبيت العتيق</div><p className="lead">Votre voyage spirituel commence<br/>bien avant le départ.</p><div className="cta"><a className="btn gold" href="#depart">Découvrir nos Omra <ArrowRight size={18}/></a><WhatsApp/></div></div><div className="side"><span>01</span><p>Votre compagnon de confiance<br/>vers les Lieux Saints.</p></div><a className="scroll" href="#voyage">DÉCOUVRIR ↓</a></section>
  <section className="intro"><div><p className="kicker">BIEN PLUS QU’UNE RÉSERVATION</p><h2>Un chemin pensé<br/>pour votre <em>sérénité.</em></h2></div><p>Chaque étape compte. De votre première question jusqu’à votre retour à Taroudant, notre rôle est de vous guider avec clarté, présence et attention.</p></section>
  <section className="journey" id="voyage"><Title n="01" k="MON VOYAGE VERS LA MAISON SACRÉE" h={<>Votre parcours,<br/>en toute confiance.</>}/><div className="route">{journey.map((j,i)=><button key={j[0]} className={step===i?'active':''} onClick={()=>setStep(i)}><span>0{i+1}</span><i/><b>{j[0]}</b><small>{j[1]}</small></button>)}</div><div className="detail"><span className="ghost">0{step+1}</span><p className="kicker">{journey[step][1]}</p><h3>{journey[step][0]}</h3><div>{journey[step].slice(2).map(x=><p key={x}><Check size={16}/>{x}</p>)}</div><a href={wa(`Salam Othmane, j’ai une question sur l’étape ${journey[step][0]}.`)}>Poser une question <ArrowRight size={16}/></a></div></section>
  <section className="match" id="match"><div className="copy"><span className="num">02</span><p className="kicker">OMRA MATCH</p><h2>Quel voyage spirituel<br/>vous <em>correspond ?</em></h2><p>Quelques réponses suffisent pour préparer une recommandation adaptée à votre rythme, votre famille et vos priorités.</p><aside><ShieldCheck/><span><b>Une approche humaine</b><small>Votre recommandation sera confirmée personnellement par Othmane.</small></span></aside></div><div className="matchCard">{match<qs.length?<><div className="progress"><span>QUESTION {match+1} SUR {qs.length}</span><i><b style={{width:`${(match+1)*25}%`}}/></i></div><h3>{qs[match][0]}</h3><div className="options">{qs[match].slice(1).map(o=><button key={o} className={answers[match]===o?'selected':''} onClick={()=>setAnswers({...answers,[match]:o})}>{o}<span>{answers[match]===o?<Check/>:<ArrowRight/>}</span></button>)}</div><button className="btn dark" disabled={!answers[match]} onClick={()=>setMatch(match+1)}>{match===3?'Voir ma recommandation':'Continuer'}<ArrowRight/></button></>:<div className="result"><Sparkles/><p className="kicker">VOTRE PROFIL</p><h3>{rec}</h3><p>Un voyage équilibré, avec un accompagnement attentif et une proximité adaptée à vos priorités.</p><WhatsApp label="Recevoir ma proposition" message={`Salam Othmane, j’ai complété Omra Match. Mon profil est ${rec}. Pouvez-vous me préparer une proposition ?`}/><button onClick={()=>{setMatch(0);setAnswers({})}}>Recommencer</button></div>}</div></section>
  <section className="explore"><Title n="03" k="EXPLORER LES LIEUX SAINTS" h={<>Comprendre avant<br/>de partir.</>}/><div className="tabs"><button className={city==='Makkah'?'active':''} onClick={()=>setCity('Makkah')}>Makkah</button><button className={city==='Médine'?'active':''} onClick={()=>setCity('Médine')}>Médine</button></div><div className="map"><div className="mapVisual"><MapPin/><i/><div><span>{city==='Makkah'?'ٱلْمَسْجِدُ ٱلْحَرَامُ':'المسجد النبوي'}</span><b>{city==='Makkah'?'Masjid Al-Haram':'Masjid An-Nabawi'}</b></div></div><div className="proximity"><p className="kicker">VISUALISEUR DE PROXIMITÉ</p><h3>De votre hôtel<br/>au cœur des lieux.</h3><Row icon={<MapPin/>} title="Votre hôtel" sub="Choisi selon votre formule"/><Row icon={<span className="dash"/>} title="Distance à confirmer" sub="Temps de marche selon l’hôtel"/><Row icon={<Compass/>} title={city==='Makkah'?'Masjid Al-Haram':'Masjid An-Nabawi'} sub="Votre destination"/><p className="note">Les distances et hôtels s’affichent dès qu’une offre vérifiée est publiée par l’agence.</p></div></div></section>
  <section className="departure" id="depart"><p className="kicker"><i/> PROCHAIN DÉPART</p><div><span><small>OMRA · PROGRAMME À VENIR</small><h2>Le prochain voyage<br/>se prépare.</h2></span><div className="meta"><Row icon={<Clock3/>} title="À confirmer" sub="DURÉE"/><Row icon={<Plane/>} title="Makkah + Médine" sub="ITINÉRAIRE"/><Row icon={<Users/>} title="À confirmer (DH)" sub="TARIF"/></div></div><WhatsApp label="Être informé du prochain départ" message="Salam Othmane, je souhaite être informé(e) du prochain départ Omra."/></section>
  <section className="family" id="famille"><div className="copy"><span className="num">04</span><p className="kicker">OMRA EN FAMILLE</p><h2>Voyager ensemble,<br/><em>sereinement.</em></h2><p>Composez votre groupe. Nous vous aidons à anticiper chambres, transferts et assistance dont chacun peut avoir besoin.</p><aside><HeartHandshake/><span><b>Une attention particulière pour nos aînés</b><small>Rythme, mobilité et accompagnement pris en compte.</small></span></aside></div><div className="builder">{([['adultes','Adultes','18 ans et +'],['enfants','Enfants','Moins de 18 ans'],['aines','Personnes âgées','Assistance possible']] as const).map(([k,l,s])=><div className="counter" key={k}><span><b>{l}</b><small>{s}</small></span><div><button onClick={()=>change(k,-1)}><Minus/></button><strong>{family[k]}</strong><button onClick={()=>change(k,1)}><Plus/></button></div></div>)}<div className="summary"><Users/><p><b>{family.adultes+family.enfants+family.aines} voyageurs</b><span>{family.aines?'Nous prévoirons une attention adaptée pour vos aînés.':'Une proposition familiale adaptée sera préparée.'}</span></p></div><WhatsApp label="Préparer notre voyage" message={`Salam Othmane, je prépare une Omra pour ${family.adultes} adulte(s), ${family.enfants} enfant(s) et ${family.aines} personne(s) âgée(s).`}/></div></section>
  <section className="guide" id="guide"><div className="guideCopy"><p className="kicker">GUIDE SPIRITUEL DIGITAL</p><h2>Se préparer,<br/>avec justesse.</h2><p>Un espace clair pour retrouver les repères pratiques et les contenus validés par un guide qualifié.</p></div><div className="guideList">{[['Avant l’Omra','Préparer son intention, ses documents et son départ.'],['Les étapes','Un parcours clair, étape après étape.'],['Les invocations','Un espace prêt pour des contenus vérifiés.'],['Conseils pratiques','Repères utiles pour voyager sereinement.']].map(([t,d],i)=><button key={t}><span>0{i+1}</span><div><b>{t}</b><small>{d}</small></div><ArrowRight/></button>)}<p className="note">Les contenus religieux sont proposés à titre informatif. Pour toute question religieuse spécifique, consultez un guide qualifié.</p></div></section>
  <section className="companion"><div className="phone"><div className="phoneTop"><Mark/><span>MON ESPACE</span><Menu/></div><p>Bonjour Ahmed 👋</p><h3>Votre Omra approche.</h3><div className="count"><b>12</b><span>jours<br/>avant le départ</span></div><div className="wallet"><small>MON VOYAGE</small><b>Date à confirmer</b><span>Taroudant → Lieux Saints</span></div><div className="checks"><b>Mes préparatifs</b>{['Passeport','Visa','Préparation spirituelle'].map((x,i)=><p key={x}><i className={i<2?'done':''}>{i<2&&<Check/>}</i>{x}</p>)}</div></div><div className="copy"><span className="num">05</span><p className="kicker">VOTRE COMPAGNON OMRA</p><h2>Tout votre voyage,<br/>dans votre poche.</h2><p>Documents, étapes, rappels et assistance réunis dans un espace personnel simple et rassurant.</p><ul><li><Check/>Documents toujours accessibles</li><li><Check/>Programme jour après jour</li><li><Check/>Assistance en un geste</li></ul><button className="btn outline" onClick={()=>alert('Aperçu client — accès sécurisé disponible après réservation.')}>Découvrir l’espace client <ArrowRight/></button></div></section>
  <section className="emotion"><div className="arabic" dir="rtl">خير رفيق للبيت العتيق</div><h2>Parce qu’un voyage vers les Lieux Saints<br/>mérite plus qu’une réservation.</h2><p>Présents avant. À vos côtés pendant. Disponibles après.</p><WhatsApp label="Échanger avec Othmane"/></section>
  <section className="instagram"><div><p className="kicker">@FANTASTIC_GOLDEN_TAROUDANT</p><h2>Suivez notre voyage<br/>sur Instagram.</h2><p>Les publications vérifiées de l’agence apparaîtront ici dès la connexion du compte.</p><a className="btn dark" href="https://instagram.com/fantastic_golden_taroudant" target="_blank">Voir le profil <ArrowRight/></a></div><div className="insta">{[1,2,3].map(n=><div key={n}><span>Contenu Instagram</span><small>À connecter</small></div>)}</div></section>
  <footer><div className="footBrand"><Mark/><span><b>FANTASTIC GOLDEN</b><i className="arabic">خير رفيق للبيت العتيق</i></span></div><div><b>Découvrir</b><a href="#voyage">Votre parcours</a><a href="#match">Omra Match</a><a href="#guide">Guide spirituel</a></div><div><b>Contact</b><a href="tel:+212665422808">06 65 42 28 08</a><a href={wa('Salam Othmane, je souhaite vous parler de mon projet de voyage.')}>WhatsApp</a><span>Taroudant, Maroc</span></div><div><b>Autres voyages</b><span>Vols · Hôtels · Circuits</span><span>Transferts · Visas</span><span>Voyages sur mesure</span></div><small>© 2026 Fantastic Golden · Informations gérées par l’agence.</small></footer>
  <a className="float" href={wa('Salam Othmane, je souhaite avoir des informations.')} target="_blank"><MessageCircle/><span>Besoin d’aide ?</span></a><nav className="mobile"><a href="#top">Accueil</a><a href="#match">Omra Match</a><a href="#guide">Guide</a><a href={wa('Salam Othmane, je souhaite avoir des informations.')}>WhatsApp</a></nav>
 </main>
}
function Title({n,k,h}:{n:string,k:string,h:React.ReactNode}){return <div className="title"><span className="num">{n}</span><p className="kicker">{k}</p><h2>{h}</h2></div>}
function Row({icon,title,sub}:{icon:React.ReactNode,title:string,sub:string}){return <div className="row">{icon}<span><small>{sub}</small><b>{title}</b></span></div>}

function ArabicHome({onFrench}:{onFrench:()=>void}){
 const [step,setStep]=useState(0),[city,setCity]=useState<'مكة'|'المدينة'>('مكة'),[family,setFamily]=useState({adults:2,children:0,elders:0});
 const stages=[['قبل السفر','التحضير','الوثائق والتأشيرة','نصائح عملية','الاستعداد الروحي'],['الرحلة','المرافقة','الطيران والنقل','استقبال المجموعة','مساعدة مستمرة'],['مكة المكرمة','العبادة','الفندق والحرم','برنامج روحاني','مرافقة'],['المدينة المنورة','السكينة','المسجد النبوي','الزيارات','لحظات إيمانية'],['العودة','المتابعة','النقل والطيران','متابعة المجموعة','ذكريات مشتركة']];
 const change=(k:keyof typeof family,d:number)=>setFamily(v=>({...v,[k]:Math.max(k==='adults'?1:0,v[k]+d)}));
 return <main className="rtl" dir="rtl" lang="ar">
  <header><a href="#ar-top" className="brand"><Mark/><span><b>FANTASTIC GOLDEN</b><small>تارودانت · المغرب</small></span></a><nav><a href="#ar-trip">رحلتكم</a><a href="#ar-match">اختيار العمرة</a><a href="#ar-guide">الدليل</a><a href="#ar-family">العائلات</a></nav><div className="actions"><button onClick={onFrench}><Languages size={16}/>Français</button><ArabicWhats label="واتساب"/></div></header>
  <section className="hero" id="ar-top"><div className="heroBg"/><div className="heroContent"><p className="kicker">رحلات العمرة · مرافقة إنسانية</p><h1>FANTASTIC<br/><em>GOLDEN</em></h1><div className="arabic">خير رفيق للبيت العتيق</div><p className="lead">رحلتكم الروحية تبدأ<br/>قبل موعد السفر.</p><div className="cta"><a className="btn gold" href="#ar-depart">اكتشفوا رحلات العمرة <ArrowRight/></a><ArabicWhats label="تحدثوا مع عثمان"/></div></div><div className="side"><span>٠١</span><p>رفيقكم الموثوق<br/>نحو الديار المقدسة.</p></div></section>
  <section className="intro"><div><p className="kicker">أكثر من مجرد حجز</p><h2>طريق صُمّم<br/>من أجل <em>طمأنينتكم.</em></h2></div><p>كل مرحلة مهمة. من أول سؤال إلى العودة إلى تارودانت، نرافقكم بالوضوح والحضور والاهتمام.</p></section>
  <section className="journey" id="ar-trip"><Title n="٠١" k="رحلتي نحو البيت العتيق" h={<>مساركم،<br/>بكل ثقة.</>}/><div className="route">{stages.map((j,i)=><button key={j[0]} className={step===i?'active':''} onClick={()=>setStep(i)}><span>٠{i+1}</span><i/><b>{j[0]}</b><small>{j[1]}</small></button>)}</div><div className="detail"><p className="kicker">{stages[step][1]}</p><h3>{stages[step][0]}</h3><div>{stages[step].slice(2).map(x=><p key={x}><Check/>{x}</p>)}</div><ArabicWhats label="اطرحوا سؤالاً" message={`السلام عليكم عثمان، لدي سؤال حول مرحلة ${stages[step][0]}.`}/></div></section>
  <section className="match" id="ar-match"><div className="copy"><span className="num">٠٢</span><p className="kicker">اختيار العمرة المناسبة</p><h2>أي رحلة روحانية<br/><em>تناسبكم؟</em></h2><p>نأخذ بعين الاعتبار الفترة، عدد المسافرين، مستوى الراحة، القرب من الحرم والميزانية بالدرهم المغربي.</p><aside><ShieldCheck/><span><b>توصية إنسانية وشخصية</b><small>يتولى عثمان تأكيد الاقتراح المناسب لكم.</small></span></aside></div><div className="matchCard result"><Sparkles/><p className="kicker">اقتراحكم الشخصي</p><h3>عمرة الراحة</h3><p>أخبرونا بأولوياتكم لنعدّ عرضاً واضحاً دون أسعار أو معلومات غير مؤكدة.</p><ArabicWhats label="استلام العرض عبر واتساب" message="السلام عليكم عثمان، أريد عرضاً شخصياً لرحلة العمرة، والأسعار بالدرهم المغربي."/><p className="note">جميع الأسعار المنشورة ستكون بالدرهم المغربي (DH).</p></div></section>
  <section className="explore"><Title n="٠٣" k="استكشفوا الديار المقدسة" h={<>افهموا المسار<br/>قبل السفر.</>}/><div className="tabs"><button className={city==='مكة'?'active':''} onClick={()=>setCity('مكة')}>مكة</button><button className={city==='المدينة'?'active':''} onClick={()=>setCity('المدينة')}>المدينة</button></div><div className="map"><div className="mapVisual"><MapPin/><i/><div><span>{city==='مكة'?'المسجد الحرام':'المسجد النبوي'}</span><b>{city}</b></div></div><div className="proximity"><p className="kicker">مقياس القرب</p><h3>من الفندق<br/>إلى المسجد.</h3><Row icon={<MapPin/>} title="فندقكم" sub="حسب العرض المختار"/><Row icon={<span className="dash"/>} title="المسافة قيد التأكيد" sub="مدة المشي حسب الفندق"/><Row icon={<Compass/>} title={city==='مكة'?'المسجد الحرام':'المسجد النبوي'} sub="وجهتكم"/><p className="note">تظهر المسافات والفنادق فور نشر معلومات موثقة من الوكالة.</p></div></div></section>
  <section className="departure" id="ar-depart"><p className="kicker"><i/> الرحلة القادمة</p><div><span><small>العمرة · البرنامج قريباً</small><h2>رحلتنا القادمة<br/>قيد التحضير.</h2></span><div className="meta"><Row icon={<Clock3/>} title="قيد التأكيد" sub="المدة"/><Row icon={<Plane/>} title="مكة + المدينة" sub="المسار"/><Row icon={<Users/>} title="قيد التأكيد (DH)" sub="السعر بالدرهم"/></div></div><ArabicWhats label="أخبروني بالرحلة القادمة"/></section>
  <section className="family" id="ar-family"><div className="copy"><span className="num">٠٤</span><p className="kicker">عمرة العائلة</p><h2>نسافر معاً،<br/><em>بطمأنينة.</em></h2><p>كوّنوا مجموعتكم لنساعدكم في اختيار الغرف والنقل والمرافقة المناسبة للجميع، مع عناية خاصة بكبار السن.</p><aside><HeartHandshake/><span><b>اهتمام خاص بكبار السن</b><small>نراعي الحركة والإيقاع والحاجة إلى المساعدة.</small></span></aside></div><div className="builder">{([['adults','البالغون','18 سنة فما فوق'],['children','الأطفال','أقل من 18 سنة'],['elders','كبار السن','مساعدة عند الحاجة']] as const).map(([k,l,s])=><div className="counter" key={k}><span><b>{l}</b><small>{s}</small></span><div><button onClick={()=>change(k,-1)}><Minus/></button><strong>{family[k]}</strong><button onClick={()=>change(k,1)}><Plus/></button></div></div>)}<div className="summary"><Users/><p><b>{family.adults+family.children+family.elders} مسافرين</b><span>سنعدّ اقتراحاً مناسباً لعائلتكم.</span></p></div><ArabicWhats label="حضّروا رحلتنا" message={`السلام عليكم عثمان، نخطط للعمرة: ${family.adults} بالغين، ${family.children} أطفال، ${family.elders} من كبار السن.`}/></div></section>
  <section className="guide" id="ar-guide"><div className="guideCopy"><p className="kicker">الدليل الروحي الرقمي</p><h2>استعدوا،<br/>بوضوح وطمأنينة.</h2><p>فضاء منظم للمعلومات العملية والمحتوى الذي يراجعه مرشد مؤهل.</p></div><div className="guideList">{[['قبل العمرة','الاستعداد للرحلة والوثائق.'],['خطوات العمرة','مسار واضح خطوة بخطوة.'],['الأدعية','مساحة مخصصة للمحتوى الموثق.'],['نصائح عملية','إرشادات لسفر أكثر راحة.']].map(([t,d],i)=><button key={t}><span>٠{i+1}</span><div><b>{t}</b><small>{d}</small></div><ArrowRight/></button>)}<p className="note">المحتوى الديني مقدم لأغراض إعلامية. لأي سؤال ديني خاص، يرجى استشارة مرشد مؤهل.</p></div></section>
  <section className="companion"><div className="phone"><div className="phoneTop"><Mark/><span>فضائي الخاص</span><Menu/></div><p>مرحباً أحمد 👋</p><h3>موعد عمرتكم يقترب.</h3><div className="count"><b>١٢</b><span>يوماً<br/>قبل السفر</span></div><div className="wallet"><small>رحلتي</small><b>التاريخ قيد التأكيد</b><span>تارودانت ← الديار المقدسة</span></div><div className="checks"><b>استعداداتي</b>{['جواز السفر','التأشيرة','الاستعداد الروحي'].map((x,i)=><p key={x}><i className={i<2?'done':''}>{i<2&&<Check/>}</i>{x}</p>)}</div></div><div className="copy"><span className="num">٠٥</span><p className="kicker">رفيق العمرة الرقمي</p><h2>كل تفاصيل رحلتكم<br/>بين أيديكم.</h2><p>الوثائق والبرنامج والتنبيهات والمساعدة في فضاء شخصي بسيط وآمن.</p><ul><li><Check/>الوثائق متاحة دائماً</li><li><Check/>برنامج يومي واضح</li><li><Check/>المساعدة بلمسة واحدة</li></ul></div></section>
  <section className="emotion"><div className="arabic">خير رفيق للبيت العتيق</div><h2>لأن الرحلة إلى الديار المقدسة<br/>تستحق أكثر من مجرد حجز.</h2><p>معكم قبل السفر، أثناء الرحلة، وبعد العودة.</p><ArabicWhats label="تواصلوا مع عثمان"/></section>
  <footer><div className="footBrand"><Mark/><span><b>FANTASTIC GOLDEN</b><i className="arabic">خير رفيق للبيت العتيق</i></span></div><div><b>اكتشفوا</b><a href="#ar-trip">مسار الرحلة</a><a href="#ar-match">اختيار العمرة</a><a href="#ar-guide">الدليل الروحي</a></div><div><b>التواصل</b><a href="tel:+212665422808">06 65 42 28 08</a><span>تارودانت، المغرب</span></div><div><b>خدمات أخرى</b><span>طيران · فنادق · جولات</span><span>نقل · تأشيرات</span><span>رحلات حسب الطلب</span></div><small>© 2026 Fantastic Golden · المعلومات والأسعار تديرها الوكالة.</small></footer>
  <a className="float" href={wa('السلام عليكم عثمان، أريد معلومات عن رحلات العمرة.')} target="_blank"><MessageCircle/><span>هل تحتاجون مساعدة؟</span></a>
 </main>
}
function ArabicWhats({label,message='السلام عليكم عثمان، أريد معلومات عن رحلات العمرة.'}:{label:string,message?:string}){return <a className="btn whats" href={wa(message)} target="_blank"><MessageCircle/>{label}</a>}
